# Cloudflare Worker 配置文件

name = "wechat-customer-service"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
name = "wechat-customer-service"
# 微信企业号配置
WECHAT_CORP_ID="123"
WECHAT_KF_SECRET="123"
WECHAT_KF_TOKEN="cZI8l4W"
WECHAT_KF_ENCODING_AES_KEY="gY2kB27cnGVsHMRoxHt24eTBgyPooAA099G2URowMyE"

# 加密服务配置（由于 CF Worker CRYPTO 兼容性问题，需要单独部署）
CRYPTO_SERVICE_URL="https://high-butterfly-79.deno.dev/"

# OpenAI API 配置
OPENAI_API_KEY="sk-1MAzwF0L2LH5bnYW1ExLREKLLCJDSWeU3su0PNbyxDWw5yth"
OPENAI_BASE_URL="http://8.137.52.146:3000/v1"
OPENAI_MODEL="gcli2api/gemini-2.5-flash"
OPENAI_TIMEOUT=30000
# OPENAI_ORGANIZATION=org-your-org-id
# OPENAI_PROJECT=proj-your-project-id

# 系统提示词配置
SYSTEM_PROMPT="your are helpful assistant, reply in chinese, and reply in plain text format, text length should be less than 10240 characters" 


# KV存储配置（用于持久化对话历史）
[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "20ab461e19d44e4d8ab05e7ebb13fd5f"
preview_id = ""

# KV存储配置（用于消息处理状态跟踪）
[[kv_namespaces]]
binding = "MESSAGE_TRACKER"
id = "c982242f8d2a4d8f9c77eeb786dc9c33"
preview_id = ""